# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 08:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('interest', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=(0.0, 0.0), geography=True, srid=4326)),
                ('localname', models.CharField(max_length=75)),
                ('color', models.CharField(choices=[('blue', 'blue'), ('orange', 'orange'), ('indigo', 'indigo'), ('brown', 'brown'), ('purple', 'purple'), ('green', 'green'), ('pink', 'pink')], default='pink', max_length=8)),
                ('name', models.CharField(max_length=75)),
                ('short', models.CharField(default='', max_length=240)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('stop', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('hashtag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SourceProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('logo', models.ImageField(null=True, upload_to='/home/django/dfwhack/server/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Upvoted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to=settings.AUTH_USER_MODEL),
        ),
    ]
